### ISSUE TITLE
Adminユーザーはタグ画像を登録できる

### ISSUE THREAD

**Issue by atman-33** [atman-33/computing-atman-v6-mk2#23]
## Overview  

Adminユーザーはタグ画像を登録できる。

### What will be done?  
Adminユーザーのみがアクセスできるタグ画像登録ページを作成する。
タグ画像登録ページでは、タグ名・タグ画像の登録/更新を可能とする。

### Why is this necessary?  
タグ画像を登録することで、画面に表示させて分かりやすくするため。

## Acceptance Criteria  
  
- [ ] タグ画像を登録できること
- [ ] タグを保存する際、画像の解像度は48x48pxで保存すること
- [ ] 一般ユーザー（Admin以外）はタグ画像を登録するページにアクセスできないこと

## Tasks  
  
- [ ] タグ画像を登録するページコンポーネントを作成する。
- [ ] タグ画像をアップロードするコンポーネントを作成する。
- [ ] タグ画像をアップロードする際、解像度を変換（48x48px）して保存する処理を実装する。

## Other  
 
Adminかどうかは、環境変数に指定したEメールアドレスが、ログインユーザーのEメールアドレスと同じかどうかで判断する。
